name: Deploy

# on 定义的是执行该 Action 的时机，这里的配置是指：
# 当 main 分支的 push 事件被触发的时候执行该任务
on:
  push:
    branches: [main]
# jobs 是定义你要运行的具体任务，
# 每个 Action 可以有多个 Job
# 每个 Job 可以有多个 Step
# 每个 Step 又可以有多个 Run
jobs:
  build:
    runs-on: ubuntu-latest # 运行在 ubuntu 系统环境下
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.10.0"
      - name: Install dependencies
        run: |
          yarn
          yarn build
      - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
        with:
          # Github 会在 workflow 中自动生成 GIHUBT_TOKEN，用于认证 workflow 的运行
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 静态资源目录设置
          publish_dir: ./build
          # 默认发布到 gh-pages 分支上，可以指定特定的发布分支（不能选拉取代码的分支）
          # publish_branch: gh-pages
          full_commit_message: ${{ github.event.head_commit.message }}
    # - name: Push To Pages
    #   working-directory: ./build # 指定下面指令运行的目录
    #   run: |
    #     git init
    #     git checkout -b main
    #     git add -A
    #   # 这里把下面所有 `<YOUR_NAME>/<YOUR_EMAIL>/<COMMIT_MSG>/<YOUR_TOKEN>` 替换成你自己的就可以了
    #     git -c user.name='zoozzzz' -c user.email='zooz_cai@163.com' commit -m 'feat:config'
    #   # 这里需要一个 共开仓库 的 secrets 配置，这里的 secrets 是一个环境变量，可以直接拿过来直接用
    #     git remote add origin https://${{secrets.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}}@github.com/zoozzzz/blog.git
    #     git push origin main -f -q
